TrashCollector/Models/Customer.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace TrashCollector.Models
{
    public class Customer
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        public double Balance { get; set; }

        [ForeignKey("Address")]
        [Display(Name = "Address")]
        public int? AddressId { get; set; }
        public Address Address { get; set; }

        [ForeignKey("Pickup")]
        [Display(Name = "Pickup Information")]
        public int? PickupId { get; set; }
        public Pickup Pickup { get; set; }
        
        [ForeignKey("IdentityUser")]
        public string? IdentityUserId { get; set; }
        public IdentityUser IdentityUser { get; set; }

    }
}

TrashCollector/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TrashCollector.Data;
using TrashCollector.Models;

namespace TrashCollector.Controllers
{
    public class CustomersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CustomersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var applicationDbContext = _context.Customer.Include(c => c.Address).Include(c => c.IdentityUser).Include(c => c.Pickup);
            var singleUser = applicationDbContext.Where(c => c.IdentityUserId == userId);
            return View(await singleUser.ToListAsync());
            //Should be working now. Should only return the current user

            //Maybe want to include buttons on the homepage that allow the user to do things, but not necessary

            //Must be something going on with the create method. It's only if it hits the create method that the list of other customers comes up
            //Create method goes to index after. Need to default to Index after login I think
        }

        public IActionResult SuspendService(int id)
        {
            //Grab customer from db. Bring up the delivery info associated with that customer. Tell them to enter the dates
            var customer = _context.Customer.Where(c => c.Id == id).FirstOrDefault();

            return View(customer);
        }

        [HttpPost]
        public async Task<IActionResult> SuspendService(Customer customer)
        {
            //Take the customer's inputs and change the days of suspension
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var currentUser = _context.Customer.Where(c => c.IdentityUserId == userId).FirstOrDefault();
            currentUser.Pickup = _context.Pickup.Where(p => p.Id == currentUser.PickupId).FirstOrDefault();
            currentUser.Pickup.SuspendedStart = customer.Pickup.SuspendedStart;
            currentUser.Pickup.SuspendedEnd = customer.Pickup.SuspendedEnd;

            currentUser.Pickup.IsSuspended = true;

            return RedirectToAction("Index");
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            //This creates a list of addresses, etc. I want to input a new one
            ViewData["IdentityUserId"] = new SelectList(_context.Users, "Id", "Id");
            //var userId = _context.UserRoles.Select(a => a).LastOrDefault(e => e.RoleId != null);
            ////This doesn't work because it tries to grab the null row at the bottom?
            //Customer customer = new Customer();
            //customer.IdentityUserId = userId.UserId;

            //I don't think any of this is going to work. The table doesn't update at the top or bottom. Weird. Need to grab most recent item

            //Somewhere around here I need to assign the most recently created userid, or grab the identityUser and assign them to the customer I'm going to create
            //I need that long string of gibberish that's already put into the AspNetUserRoles table so I can grab the user and put them into the IdentityUser column in the Customer table???
            return View();
            //I want to require an address when they are created
            //How to attach the user.Id to the customer.Id??

            //Could have them create an address during registration, then choose that address from a dropdown list
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Balance,AddressId,PickupId,IdentityUserId")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                customer.IdentityUserId = userId;
                customer.Pickup = new Pickup();

                _context.Customer.Add(customer);
                _context.SaveChanges();
                return RedirectToAction("Create", "Addresses");
            }
            ViewData["AddressId"] = new SelectList(_context.Set<Address>(), "Id", "Id", customer.AddressId);
            ViewData["IdentityUserId"] = new SelectList(_context.Users, "Id", "Id", customer.IdentityUserId);
            ViewData["PickupId"] = new SelectList(_context.Set<Pickup>(), "Id", "Id", customer.PickupId);

            return View(customer);
        }

        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var customer = _context.Customer.Where(c => c.Id == id).FirstOrDefault();
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Customer customer)
        {
            var pickup = _context.Pickup.Where(p => p.Id == customer.PickupId).FirstOrDefault();
            pickup.PickupDay = customer.Pickup.PickupDay;
            var address = _context.Address.Where(a => a.Id == customer.AddressId).FirstOrDefault();
            var idUser = _context.Users.Where(u => u.Id == customer.IdentityUserId).FirstOrDefault();

            customer.Pickup = pickup;
            //This overwrites any updates they have made to the pickup day
            customer.Address = address;
            customer.IdentityUser = idUser;
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AddressId"] = new SelectList(_context.Set<Address>(), "Id", "Id", customer.AddressId);
            ViewData["PickupId"] = new SelectList(_context.Set<Pickup>(), "Id", "Id", customer.PickupId);
            return View(customer);
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer
                .Include(c => c.Address)
                .Include(c => c.IdentityUser)
                .Include(c => c.Pickup)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customer = await _context.Customer.FindAsync(id);
            _context.Customer.Remove(customer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CustomerExists(int id)
        {
            return _context.Customer.Any(e => e.Id == id);
        }
    }
}

TrashCollector/Controllers/PickupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TrashCollector.Data;
using TrashCollector.Models;

namespace TrashCollector.Controllers
{
    public class PickupsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PickupsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Pickups
        public async Task<IActionResult> Index()
        {
            return View(await _context.Pickup.ToListAsync());
        }

        // GET: Pickups/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pickup = await _context.Pickup
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pickup == null)
            {
                return NotFound();
            }

            return View(pickup);
        }

        // GET: Pickups/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pickups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PickupDay,IsSuspended,SuspendedStart,SuspendedEnd,OneTimePickup")] Pickup pickup)
        {
            if (ModelState.IsValid)
            {
                _context.Pickup.Add(pickup);
                await _context.SaveChangesAsync();
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                var currentUser = _context.Customer.Where(c => c.IdentityUserId == userId).FirstOrDefault();
                currentUser.PickupId = pickup.Id;
                currentUser.Pickup = pickup;
                //it doesn't actually save the pickup or the address. Do that later
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Customers");
            }
            return View(pickup);
        }

        // GET: Pickups/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pickup = await _context.Pickup.FindAsync(id);
            if (pickup == null)
            {
                return NotFound();
            }
            return View(pickup);
        }

        // POST: Pickups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PickupDay,IsSuspended,SuspendedStart,SuspendedEnd,OneTimePickup")] Pickup pickup)
        {
            if (id != pickup.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pickup);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PickupExists(pickup.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pickup);
        }

        // GET: Pickups/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pickup = await _context.Pickup
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pickup == null)
            {
                return NotFound();
            }

            return View(pickup);
        }

        // POST: Pickups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pickup = await _context.Pickup.FindAsync(id);
            _context.Pickup.Remove(pickup);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PickupExists(int id)
        {
            return _context.Pickup.Any(e => e.Id == id);
        }
    }
}

TrashCollector/Views/Customers/Create.cshtml
@model TrashCollector.Models.Customer

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TrashCollector/Views/Customers/Delete.cshtml
@model TrashCollector.Models.Customer

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Balance)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Balance)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pickup)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pickup.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdentityUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdentityUser.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TrashCollector/Views/Customers/Edit.cshtml
@model TrashCollector.Models.Customer

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pickup.OneTimePickup" class="control-label"></label>
                <input asp-for="Pickup.OneTimePickup" class="form-control">
                <span asp-validation-for="Pickup.OneTimePickup" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Pickups" asp-action="Edit" asp-route-id=@Model.PickupId>Edit Pickup Info</a>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TrashCollector/Views/Customers/Index.cshtml
@model IEnumerable<TrashCollector.Models.Customer>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Welcome!</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Balance)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pickup.PickupDay)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
            //Only show the customer who is currently signed in here. Not all customers
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    $@Html.DisplayFor(modelItem => item.Balance)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address.StreetAddress)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Pickup.PickupDay)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Make Account Changes</a> |
                    <a asp-action="SuspendService">Suspend services</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete Account</a>
                </td>
            </tr>
        }
    </tbody>
</table>

TrashCollector/Views/Customers/SuspendService.cshtml
@model TrashCollector.Models.Customer
@{
    ViewData["Title"] = "SuspendService";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>SuspendService</h1>


<table class="table">
    <tbody>
        <form asp-action="SuspendService">
            <div class="form-group">
                <label asp-for="Pickup.SuspendedStart" class="control-label"></label>
                <input asp-for="Pickup.SuspendedStart" class="form-control" />
                <span asp-validation-for="Pickup.SuspendedStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pickup.SuspendedEnd" class="control-label"></label>
                <input asp-for="Pickup.SuspendedEnd" class="form-control" />
                <span asp-validation-for="Pickup.SuspendedEnd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </form>
    </tbody>
</table>